spring:
  config:
    activate:
      on-profile: network

network:
  process:
    command:
      managed: ${MANAGED_COMMAND}
      monitor: ${MONITOR_COMMAND}
    password: ${SUDO_PASSWORD}
  interface:
    monitor: ${MONITOR_INTERFACE}
