spring:
  config:
    import:
      # env
      - "classpath:env-main-api.properties"
      # 에코노베이션 동방들과 와이파이 세팅
      - "classpath:env-rooms-setting.yml"
      #domain-jpa 모듈의 설정 파일
      - "classpath:application-domain-jpa.yml"
      #domain-jpa가 사용할 환경 변수
      - "classpath:env-domain-jpa.properties"
      #api-query-jpa 모듈의 설정 파일
      - "classpath:application-api-query-jpa.yml"
      #logging 모듈의 설정 파일
      - "classpath:application-logging.yml"
logging:
  config: "classpath:logback-common.xml"
#  level:
#    org.springframework.security: DEBUG

frontend:
  base-url: ${FRONTEND_URL}

api-key: ${API_KEY}

https-enabled: ${HTTPS_ENABLED}

oauth:
  redirectUri: ${OAUTH_REDIRECT_URL}
  kakao:
    secret: ${KAKAO_SECRET}
    clientId : ${KAKAO_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 2h
  refresh-token-expiry: 30d
  oauth2-temp-token-expiry: 5m
