spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import:
      - "file:./env/main-api.properties"
      - "file:./env/main-api.yml"
      #모듈 별 application.yml
      - "classpath:application-domain-jpa.yml"
      - "classpath:application-api-query-jpa.yml"
      - "classpath:application-logging.yml"


frontend:
  base-url: ${FRONTEND_URL}

api-key: ${API_KEY}

https-enabled: ${HTTPS_ENABLED}

oauth:
  redirect-uri: ${OAUTH_REDIRECT_URL}
  kakao:
    secret: ${KAKAO_SECRET}
    clientId : ${KAKAO_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 2h
  refresh-token-expiry: 30d
  oauth2-temp-token-expiry: 5m

#  level:
#    org.springframework.security: DEBUG