spring:
  config:
    #domain-jpa 모듈
    import: "classpath:application-domain-jpa.yml"
logging:
  config: "classpath:logback-common.xml"

oauth:
  redirectUri: ${OAUTH_REDIRECT_URL}
  kakao:
    secret: ${KAKAO_SECRET}
    clientId : ${KAKAO_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 2h
  refresh-token-expiry: 14d
  oauth2-login-token-expiry: 10m
