spring:
  config:
    import:
      #domain-jpa 모듈의 설정 파일
      - "classpath:application-domain-jpa.yml"
      #api-query-jpa 모듈의 설정 파일
      - "classpath:application-api-query-jpa.yml"
      #logging 모듈의 설정 파일
      - "classpath:application-logging.yml"
logging:
  config: "classpath:logback-common.xml"

oauth:
  redirectUri: ${OAUTH_REDIRECT_URL}
  kakao:
    secret: ${KAKAO_SECRET}
    clientId : ${KAKAO_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 2h
  refresh-token-expiry: 14d
  oauth2-temp-token-expiry: 3m
