spring:
  config:
    import:
      - "classpath:application-shared-jpa.yml"

domain-jpa:
  hibernate:
    ddl-auto: validate
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show_sql: false
    format-sql: false