spring:
  jpa:
    open-in-view: false
  config:
    import: "classpath:env-domain-jpa.properties"

domain-jpa:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
  hibernate:
    ddl-auto: validate
    show_sql: false

logging:
  level:
    root: info

