spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import:
      # 필요한 환경 변수 가져옴 (상대경로는 user.dir이 기준)
      - "file:./env/network-api.properties"
      - "file:./env/network-api.yml"
      #logging 모듈
      - "classpath:application-logging.yml"
      #domain-jpa 모듈
      - "classpath:application-domain-jpa.yml"

server:
  port: 2471 # 24시간 운영 + network-api니까 1번째

sudo-password: ${SUDO_PASSWORD:}

command:
  managed:
    mdns: "tshark -l -i {{interface}} -Y mdns -T fields -e eth.src -e ip.src -e dns.ptr.domain_name"
    arp: "arp-scan --interface={{interface}} --localnet"
  monitor: "tshark -l -i {{interface}} -T fields -e wlan.sa -e wlan.ra"

#TODO: main-api랑 같이 공동으로 관리해야 할듯
frontend:
  base-url: ${FRONTEND_URL}

main-api:
  base-url: ${MAIN_API_BASE_URL}
  api-key: ${MAIN_API_API_KEY}