spring:
  config:
    import:
      #이 모듈의 설정 값
      - "classpath:env-network-api.properties"
      #해당 room의 network interface 설정 파일
      - "classpath:env-room-setting.yml"
      #logging 모듈의 설정 파일
      - "classpath:application-logging.yml"
      #domain-jpa 모듈의 설정 파일
      - "classpath:application-domain-jpa.yml"
      #domain-jpa 모듈의 데이터 소스 설정 파일
      - "classpath:env-domain-jpa.properties"

command:
  managed:
    mdns: "sudo -S tshark -l -i {{interface}} -Y mdns -T fields -e eth.src -e ip.src -e dns.ptr.domain_name"
    arp: "sudo -S arp-scan --interface={{interface}} --localnet"
  monitor: "sudo -S tshark -l -i {{interface}} -T fields -e wlan.sa -e wlan.ra"

sudo_password: ${SUDO_PASSWORD}

#TODO: main-api랑 같이 공동으로 관리해야 할듯
frontend:
  base-url: ${FRONTEND_URL}

main-api:
  base-url: ${MAIN_API_BASE_URL}
  api-key: ${MAIN_API_API_KEY}

logging:
  config: "classpath:logback-common.xml"