name: main-api 워크 플로우

on:
    push:
        branches:
            - develop

jobs:
    test:
        name: 테스트하기
        uses: ./.github/workflows/ci.yml

    deploy:
        if: "contains(github.event.head_commit.modified, 'modules/main-api/') ||
                     contains(github.event.head_commit.added, 'modules/main-api/') ||
                     contains(github.event.head_commit.removed, 'modules/main-api/')"
        name: 배포하기
        needs: test
        uses: ./.github/workflows/deploy.yml
        secrets:
            HOST: ${{ secrets.MAIN_API_ADDRESS }}
            USERNAME: ${{ secrets.MAIN_API_USERNAME }}
            PASSWORD: ${{ secrets.MAIN_API_PASSWORD }}
            SSH_PORT: ${{ secrets.MAIN_API_SSH_PORT }}
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
            environment: main-api